### ISSUE TITLE
checking level 3 verbiage incorrect

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#92] opened 2015-05-12 01:04 UTC

**Comment by bknatterud** [comment] 2015-05-12 18:51
This is not assigned to me so I am assuming it is not for me, but just thought I would check. If it is for me I'm not sure what the problem is. Can you explain?

**Comment by jag3773** [comment] 2015-05-12 20:51
Yes, this one is for you.  The checking level 3 description does not match what's on https://unfoldingword.org/quality/.

**Closed** 2015-05-12 22:34 UTC
