### ISSUE TITLE
Remove the "X" ability that deletes a resource

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#64] opened 2015-04-15 11:04 UTC
This function could be moved to be under the "information" drop down for a given resource.

**Comment by bknatterud** [comment] 2015-04-15 16:38
I think that if we just give the user a confirmation of delete this should be ok, no? Because, if I am the user I probably would not look for deleting a version in the info section. No?

**Comment by bknatterud** [comment] 2015-04-29 12:31
duplicate of #74

**Comment by jag3773** [comment] 2015-05-04 21:29
The Delete button is huge.  Can we please make it harder to delete content, that's the whole point here.

**Comment by bknatterud** [comment] 2015-05-04 21:32
There is a confirmation dialogue. What size do you want the delete button to be?

**Comment by bknatterud** [comment] 2015-05-05 13:11
We have reversed the colors on the button. Hopefully that will make it acceptable.

**Closed by bknatterud** 2015-05-05 13:11 UTC
