### ISSUE TITLE
Assamese ULB Causing Crash

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/uw-android#181] opened 2016-11-30 23:06 UTC
We are aware of an issue that causes the unfoldingWord Android app to crash when opening the Assamese ULB NT.

**Comment by jag3773** [comment] 2016-12-06 19:36
@bknatterud From Chris K. : 

Technically it no longer crashes as in reporting that it has stopped. After doing the language update and opening Assamese, the Bible text is displayed as expected. When I swipe left to load the next chapter, it does update the screen although chapter 1 is still indicated at the top. Additional swipes left do no cause the text to update, and after several seconds, the "unfoldingWord isn't responding" message comes up. Clicking the Wait link clears the error dialog, but from all I can tell the app is hung as no clicking or swiping causes anything except the not responding message. The only way I could get back to where uW was working at all was to uninstall the app, reboot the device, and then reinstall the app. Testing was done on an Android 5.1.1 Nexus tablet. (Do the devs not have a device that they can use for testing?)

**Comment by bknatterud** [comment] 2016-12-06 19:43
We will take a look sometime tomorrow.

**Comment by bknatterud** [comment] 2016-12-07 20:55
@jag3773 try this version 
https://github.com/unfoldingWord-dev/uw-android/releases/tag/2.3.1-beta2

**Comment by cckozie** [comment] 2016-12-08 00:30
@jag3773 The reference problems appears to be fixed in 2.3.1-beta2, although I did notice a couple issues that you may want to address:
1. If the app had crashed because of the bug that caused this issue, the app must be uninstalled before installing the new app. If it is not first uninstalled, it will continue to crash after the update. At that point uninstalling and reinstalling will work too.
2. It still shows as version 2.3.0 on the splash screen and when viewed in Android Settings/Apps

**Comment by bknatterud** [comment] 2016-12-11 04:34
@cckozie try this new version...

https://github.com/unfoldingWord-dev/uw-android/releases/tag/2.0.1-beta4

**Comment by cckozie** [comment] 2016-12-20 18:03
@jag3773 The issues mentioned above have been resolved. I did notice a couple of other things that you may or may not want to address.
1. The release should probably be named 2.3.1-beta4 rather than 2.0.1-beta4
2. I started with the version available on the Play Store (2.3.0). I ran the update, then downloaded the Assamese, and tried to view it which caused the crash. I then installed 2.3.1 beta4 without first uninstalling the old one. With the new app installed, I again had to download the Assamese text before I could use it. I don't know if that is the intended behavior or not.
3. It would be nice to have some sort of a splash screen displayed while the app is opening the first time rather than just seeing a blank window.

**Closed** 2017-01-18 00:10 UTC
Labels: bug
